### ISSUE TITLE
Information on direction

### ISSUE THREAD

**Issue by gareth-ellis** [bosch-thermostat/bosch-thermostat-client-python#4]
Hello,

I've been using the http client (under moustic999) for a while and noticed it hadnt been updated for some time. When the new app version was released i saw we could now get energy usage in the app, so wanted to be able to pull it via the api instead - that's when I came across this fork.

I'd like to know what the plan for this project is, and where any help might be required.

I'm a software engineer and happy to help - just need to know what needs doing really - I'm a little unsure what is working in the app but not allowed by my heatpump, and what should work but doesn't

For example I have an IVT heatpump, and can't get any energy usage info - even by using the recordings endpoint - as I say, i dont know if that's supposed to be possible or not - the app must be getting it from somewhere, though I have been unable to decrypt the sniffed traffic.

Thanks

Gareth

**Comment by slovdahl** [comment]
I'm also interested in helping out wherever needed!

I have a Bosch Compress 7001i at home that didn't work out of the box, so I opened #3 where I try to add support for it. I got it working in HASS to some extent, but it's not yet 100%. But let's continue that discussion in #3.

**Comment by pszafer** [comment]
Hi, @gareth-ellis I developed library under moustic999 but moustic hadn't much time to help me out last year, so I decided to make a fork, so I can release new version when I'm ready for it.

- about energy usage - make rawscan and we can see if it is in the gateway or it is somehow calculated in bosch servers,

What you can do.
First thing to do would be automatic tests with tox or some other tool.
I made simulator for it which loads rawscan as json and try to react as bosch gateway.
It can make GET and very simple PUT, which would just edit key which was send to edit and there is need for algorithm which would edit other keys as well if needed... (eg if there is schedule set up, then currentSetpoint need to be changed).
If this editor would be smart enough, then I think automatic tests can be done against multiple rawscans, for IVT EMS, IVT CAN, NEFIT etc.

This would be step one, step two would be add tests to HA component,
Step 3, remove delays on startup of component, which I made because of too many requests to bosch gateway... It might be that now in new HA version components loading are not blocking whole HA from loading so those delays are not needed anymore.

Step 4. Fix reconnection (if lost) to gateway without needed to restart HA.

**Comment by slovdahl** [comment]
After I saw this issue and wrote my comment above I also found the [Discord channel](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#first-config-help-needed), join if you feel like it @gareth-ellis 🙂
